name: all_exit_codes
description: Just terminal exit codes with more description to use in dart
version: 2.1.4
repository: https://github.com/insign/dart_all_exit_codes
homepage: https://github.com/insign/dart_all_exit_codes

environment:
  sdk: ">=3.0.0 <4.0.0"

platforms:
  linux:
  macos:
  windows:

dev_dependencies:
  lints: ^6.0.0
  test: ^1.21.0
