name: all_exit_codes
description: Just terminal exit codes with more description to use in dart
version: 2.1.2
repository: https://github.com/insign/dart_all_exit_codes
homepage: https://github.com/insign/dart_all_exit_codes

environment:
  sdk: '>=2.17.0 <3.8.0'

platforms:
  linux:
  macos:
  windows:

dev_dependencies:
  lints: ^5.1.1
  test: ^1.21.0
