// THIS FILE WAS GENERATED BY yaml2dart. EDIT IS NOT RECOMMENDED.
const name = 'all_exit_codes';
const description = 'Just terminal exit codes with more description to use in dart';
const version = '2.2.0';
const repository = 'https://github.com/insign/dart_all_exit_codes';
const homepage = 'https://github.com/insign/dart_all_exit_codes';
const environment = '{sdk: >=3.0.0 <4.0.0}';
const platforms = '{linux: null, macos: null, windows: null}';
const devDependencies = '{lints: ^6.0.0, test: ^1.21.0}';
